openapi: 3.0.0
info:
  title: "API_ResidentService"
  description: "API Services"
  version: "20241103150102"
servers:
  - url: https://staging.comforta.yukon.software/api
paths:
  /auth/resident-login:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.LoginWithQrCode"
      summary: "Login Resident Account (QR Code)"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginWithQrCodeInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_LoginResidentResponse"  

        404:
          description: "Not found"

  /auth/resident:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetResidentInformation"
      summary: "Get Resident Information"
      security: 
        - oAuthGXGAM: []
      parameters:
        - name: "Userid"
          in: "query"
          required: false
          schema:
            type: "string"
            
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Resident"  

        404:
          description: "Not found"

  /resident/organisation:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetOrganisationInformation"
      summary: "Get Organisation Information"
      security: 
        - oAuthGXGAM: []
      parameters:
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Organisation"  

        404:
          description: "Not found"

  /resident/location:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetLocationInformation"
      summary: "Get Location Information"
      security: 
        - oAuthGXGAM: []
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Location"  

        404:
          description: "Not found"

  /mobile/register-device:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.RegisterDevice"
      summary: "Register Resident Device Information"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDeviceInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /mobile/send-notification:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.SendNotification"
      summary: "Send Push Notification"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendNotificationInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/pages:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetPagesInformation"
      summary: "Get Pages Information"
      security: 
        - oAuthGXGAM: []
      parameters:
        - name: "Trn_Pageid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_Page"  

        404:
          description: "Not found"

  /media/upload:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.UploadMedia"
      summary: "UploadMedia"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadMediaInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trn_Media"  

        404:
          description: "Not found"

  /toolbox/pages/list:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetPages"
      summary: "Get Pages"
      security: 
        - oAuthGXGAM: []
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_Page"  

        404:
          description: "Not found"

  /toolbox/create-page:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.CreatePage"
      summary: "Create Page"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/save-page:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.SavePage"
      summary: "Save Page"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SavePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/update-page:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.UpdatePage"
      summary: "Update Page"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/add-page-children:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.AddPageCildren"
      summary: "Add Page CHildren"
      security: 
        - oAuthGXGAM: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPageCildrenInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

components:
  securitySchemes:
    oAuthGXGAM:
      type: oauth2
      description: GAM OAuth 2
      flows:
        password:          
          tokenUrl: http://staging.comforta.yukon.software/oauth/gam/v2.0/access_token
          scopes: 
            fullcontrol: Full access

  schemas:
    LoginWithQrCodeInput:  
      properties:
        secretKey:
          type: "string"




    RegisterDeviceInput:  
      properties:
        DeviceToken:
          type: "string"
        DeviceID:
          type: "string"
        DeviceType:
          type: "integer"
          format: "int32"
        NotificationPlatform:
          type: "string"
        NotificationPlatformId:
          type: "string"
        userId:
          type: "string"

    SendNotificationInput:  
      properties:
        title:
          type: "string"
        message:
          type: "string"


    UploadMediaInput:  
      properties:
        MediaId:
          type: "string"
          format: "uuid"
        MediaName:
          type: "string"
        MediaImageData:
          type: "string"
        MediaSize:
          type: "integer"
          format: "int64"
        MediaType:
          type: "string"


    CreatePageInput:  
      properties:
        PageName:
          type: "string"

    SavePageInput:  
      properties:
        PageId:
          type: "string"
          format: "uuid"
        PageJsonContent:
          type: "string"
        PageGJSHtml:
          type: "string"
        PageGJSJson:
          type: "string"
        SDT_Page:
          description: "SDT_Page"
          $ref: "#/components/schemas/SDT_Page"

    UpdatePageInput:  
      properties:
        PageId:
          type: "string"
          format: "uuid"
        PageJsonContent:
          type: "string"
        PageGJSHtml:
          type: "string"
        PageGJSJson:
          type: "string"

    AddPageCildrenInput:  
      properties:
        ParentPageId:
          type: "string"
          format: "uuid"
        ChildPageId:
          type: "string"
          format: "uuid"
  
    SDT_LoginResidentResponse:
      properties:
        access_token:
          description: "access_token"
          type: "string"
        token_type:
          description: "token_type"
          type: "string"
        expires_in:
          description: "expires_in"
          type: "number"
          format: "double"
        refresh_token:
          description: "refresh_token"
          type: "string"
        scope:
          description: "scope"
          type: "string"
        user_guid:
          description: "user_guid"
          type: "string"



    SDT_Resident:
      properties:
        ResidentId:
          description: "Resident Id"
          type: "string"
          format: "uuid"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        ResidentSalutation:
          description: "Resident Salutation"
          type: "string"
        ResidentBsnNumber:
          description: "Resident Bsn Number"
          type: "string"
        ResidentGivenName:
          description: "Resident Given Name"
          type: "string"
        ResidentLastName:
          description: "Resident Last Name"
          type: "string"
        ResidentInitials:
          description: "Resident Initials"
          type: "string"
        ResidentEmail:
          description: "Resident Email"
          type: "string"
        ResidentGender:
          description: "Resident Gender"
          type: "string"
        ResidentAddress:
          description: "Resident Address"
          type: "string"
        ResidentPhone:
          description: "Resident Phone"
          type: "string"
        ResidentBirthDate:
          description: "Resident Birth Date"
          type: "string"
          format: "date"
        ResidentGUID:
          description: "Resident GUID"
          type: "string"
        ResidentTypeId:
          description: "Resident Type Id"
          type: "string"
          format: "uuid"
        ResidentTypeName:
          description: "Resident Type Name"
          type: "string"
        MedicalIndicationId:
          description: "Medical Indication Id"
          type: "string"
          format: "uuid"
        MedicalIndicationName:
          description: "Medical Indication Name"
          type: "string"



    SDT_Organisation:
      properties:
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        OrganisationName:
          description: "Organisation Name"
          type: "string"
        OrganisationKvkNumber:
          description: "Organisation Kvk Number"
          type: "string"
        OrganisationEmail:
          description: "Organisation Email"
          type: "string"
        OrganisationPhone:
          description: "Organisation Phone"
          type: "string"
        OrganisationVATNumber:
          description: "Organisation VATNumber"
          type: "string"
        OrganisationCountry:
          description: "Organisation Address Country"
          type: "string"
        OrganisationCity:
          description: "Organisation Address City"
          type: "string"
        OrganisationZipCode:
          description: "Organisation Address Zip Code"
          type: "string"
        OrganisationAddressLine1:
          description: "Organisation Address Line1"
          type: "string"
        OrganisationAddressLine2:
          description: "Organisation Address Line2"
          type: "string"
        OrganisationTypeId:
          description: "Organisation Type Id"
          type: "string"
          format: "uuid"
        OrganisationTypeName:
          description: "Organisation Type Name"
          type: "string"



    SDT_Location:
      properties:
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        LocationName:
          description: "Location Name"
          type: "string"
        LocationCountry:
          description: "Location Country"
          type: "string"
        LocationCity:
          description: "Location City"
          type: "string"
        LocationZipCode:
          description: "Location Zip Code"
          type: "string"
        LocationAddressLine1:
          description: "Location Address Line1"
          type: "string"
        LocationAddressLine2:
          description: "Location Address Line2"
          type: "string"
        LocationEmail:
          description: "Location Email"
          type: "string"
        LocationPhone:
          description: "Location Phone"
          type: "string"
        LocationDescription:
          description: "Location Description"
          type: "string"



    SDT_Page:
      properties:
        PageId:
          description: "Page Id"
          type: "string"
          format: "uuid"
        PageName:
          description: "Page Name"
          type: "string"
        Theme:
          description: "SDT_Theme"
          $ref: "#/components/schemas/SDT_Theme"
        PageIsPublished:
          description: "Page Is Published"
          type: "boolean"
        PageGJSJson:
          description: "Page GJSJson"
          type: "string"
        PageGJSHtml:
          description: "Page GJSHtml"
          type: "string"
        PageJsonContent:
          description: "Page Json Content"
          type: "string"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        Row:
          description: "SDT_Row"
          type: array
          items:
            $ref: "#/components/schemas/SDT_Row"



    Trn_Media:
      properties:
        MediaId:
          description: "Media Id"
          type: "string"
          format: "uuid"
        MediaName:
          description: "Media Name"
          type: "string"
        MediaImage:
          description: "Media Image"
          type: "string"
        MediaSize:
          description: "Media Size"
          type: "integer"
          format: "int64"
        MediaType:
          description: "Media Type"
          type: "string"
        MediaUrl:
          description: "Media Url"
          type: "string"



    SDT_Col:
      properties:
        ColId:
          description: "Col Id"
          type: "string"
          format: "uuid"
        ColName:
          description: "Col Name"
          type: "string"
        Tile:
          description: "SDT_Tile"
          $ref: "#/components/schemas/SDT_Tile"



    SDT_Row:
      properties:
        RowId:
          description: "Row Id"
          type: "string"
          format: "uuid"
        RowName:
          description: "Row Name"
          type: "string"
        Col:
          description: "SDT_Col"
          type: array
          items:
            $ref: "#/components/schemas/SDT_Col"



    SDT_Theme:
      properties:
        Trn_ThemeId:
          description: "Trn_Theme Id"
          type: "string"
          format: "uuid"
        Trn_ThemeName:
          description: "Trn_Theme Name"
          type: "string"
        Trn_ThemeFontFamily:
          description: "Trn_Theme Font Family"
          type: "string"
        Trn_ThemeFontSize:
          description: "Trn_Theme Font Size"
          type: "integer"
          format: "int32"



    SDT_Tile:
      properties:
        TileId:
          description: "Tile Id"
          type: "string"
          format: "uuid"
        TileName:
          description: "Tile Name"
          type: "string"
        TileText:
          description: "Tile Text"
          type: "string"
        TileTextColor:
          description: "Tile Text Color"
          type: "string"
        TileTextAlignment:
          description: "Tile Text Alignment"
          type: "string"
        TileIcon:
          description: "Tile Icon"
          type: "string"
        TileIconColor:
          description: "Tile Icon Color"
          type: "string"
        TileIconAlignment:
          description: "Tile Icon Alignment"
          type: "string"
        TileBGColor:
          description: "Tile BGColor"
          type: "string"
        TileBGImageUrl:
          description: "Tile BGImage Url"
          type: "string"
        TileBGImageOpacity:
          description: "Tile BGImage Opacity"
          type: "integer"
          format: "int32"
        TileAction:
          description: "SDT_Tile Action"
          $ref: "#/components/schemas/SDT_TileAction"



    SDT_TileAction:
      properties:
        ObjectType:
          description: "Object Type"
          type: "string"
        ObjectId:
          description: "Object Id"
          type: "string"
          format: "uuid"



 
