openapi: 3.0.0
info:
  title: "API_ToolBoxService"
  description: "API_Tool Box Service"
  version: "20241114060012"
servers:
  - url: https://staging.comforta.yukon.software/api
paths:
components:
  schemas:
  
 
