openapi: 3.0.0
info:
  title: "API_ResidentService"
  description: "API Services"
  version: "20241114054145"
servers:
  - url: https://staging.comforta.yukon.software/api
paths:
  /auth/resident-login:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.LoginWithQrCode"
      summary: "Login Resident Account (QR Code)"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginWithQrCodeInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_LoginResidentResponse"  

        404:
          description: "Not found"

  /auth/resident:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetResidentInformation"
      summary: "Get Resident Information"
      parameters:
        - name: "Userid"
          in: "query"
          required: false
          schema:
            type: "string"
            
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Resident"  

        404:
          description: "Not found"

  /resident/organisation:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetOrganisationInformation"
      summary: "Get Organisation Information"
      parameters:
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Organisation"  

        404:
          description: "Not found"

  /resident/location:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.GetLocationInformation"
      summary: "Get Location Information"
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Location"  

        404:
          description: "Not found"

  /mobile/register-device:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.RegisterDevice"
      summary: "Register Resident Device Information"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDeviceInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /mobile/send-notification:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.SendNotification"
      summary: "Send Push Notification"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendNotificationInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /location/agenda:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.AgendaLocation"
      summary: "Location Agenda"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AgendaLocationInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_AgendaLocation"  

        404:
          description: "Not found"

  /form/dynamic-form:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.SendDynamicForm"
      summary: "Send Test Dynamic form"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /media/upload:
    post:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.UploadMedia"
      summary: "UploadMedia"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadMediaInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trn_Media"  

        404:
          description: "Not found"

  /productservice:
    get:
      tags:
        - API_ResidentService  
      operationId: "API_ResidentService.ProductSericeAPI"
      summary: "ProductService API"
      parameters:
        - name: "Productserviceid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_ProductService"  

        404:
          description: "Not found"

components:
  schemas:
    LoginWithQrCodeInput:  
      properties:
        secretKey:
          type: "string"




    RegisterDeviceInput:  
      properties:
        DeviceToken:
          type: "string"
        DeviceID:
          type: "string"
        DeviceType:
          type: "integer"
          format: "int32"
        NotificationPlatform:
          type: "string"
        NotificationPlatformId:
          type: "string"
        userId:
          type: "string"

    SendNotificationInput:  
      properties:
        title:
          type: "string"
        message:
          type: "string"

    AgendaLocationInput:  
      properties:
        locationId:
          type: "string"
          format: "uuid"


    UploadMediaInput:  
      properties:
        MediaId:
          type: "string"
          format: "uuid"
        MediaName:
          type: "string"
        MediaImageData:
          type: "string"
        MediaSize:
          type: "integer"
          format: "int64"
        MediaType:
          type: "string"

  
    SDT_LoginResidentResponse:
      properties:
        access_token:
          description: "access_token"
          type: "string"
        token_type:
          description: "token_type"
          type: "string"
        expires_in:
          description: "expires_in"
          type: "number"
          format: "double"
        refresh_token:
          description: "refresh_token"
          type: "string"
        scope:
          description: "scope"
          type: "string"
        user_guid:
          description: "user_guid"
          type: "string"



    SDT_Resident:
      properties:
        ResidentId:
          description: "Resident Id"
          type: "string"
          format: "uuid"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        ResidentSalutation:
          description: "Resident Salutation"
          type: "string"
        ResidentBsnNumber:
          description: "Resident Bsn Number"
          type: "string"
        ResidentGivenName:
          description: "Resident Given Name"
          type: "string"
        ResidentLastName:
          description: "Resident Last Name"
          type: "string"
        ResidentInitials:
          description: "Resident Initials"
          type: "string"
        ResidentEmail:
          description: "Resident Email"
          type: "string"
        ResidentGender:
          description: "Resident Gender"
          type: "string"
        ResidentAddress:
          description: "Resident Address"
          type: "string"
        ResidentPhone:
          description: "Resident Phone"
          type: "string"
        ResidentBirthDate:
          description: "Resident Birth Date"
          type: "string"
          format: "date"
        ResidentGUID:
          description: "Resident GUID"
          type: "string"
        ResidentTypeId:
          description: "Resident Type Id"
          type: "string"
          format: "uuid"
        ResidentTypeName:
          description: "Resident Type Name"
          type: "string"
        MedicalIndicationId:
          description: "Medical Indication Id"
          type: "string"
          format: "uuid"
        MedicalIndicationName:
          description: "Medical Indication Name"
          type: "string"



    SDT_Organisation:
      properties:
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        OrganisationName:
          description: "Organisation Name"
          type: "string"
        OrganisationKvkNumber:
          description: "Organisation Kvk Number"
          type: "string"
        OrganisationEmail:
          description: "Organisation Email"
          type: "string"
        OrganisationPhone:
          description: "Organisation Phone"
          type: "string"
        OrganisationVATNumber:
          description: "Organisation VATNumber"
          type: "string"
        OrganisationCountry:
          description: "Organisation Address Country"
          type: "string"
        OrganisationCity:
          description: "Organisation Address City"
          type: "string"
        OrganisationZipCode:
          description: "Organisation Address Zip Code"
          type: "string"
        OrganisationAddressLine1:
          description: "Organisation Address Line1"
          type: "string"
        OrganisationAddressLine2:
          description: "Organisation Address Line2"
          type: "string"
        OrganisationTypeId:
          description: "Organisation Type Id"
          type: "string"
          format: "uuid"
        OrganisationTypeName:
          description: "Organisation Type Name"
          type: "string"
        OrganisationLogo:
          description: "Organisation Logo"
          type: "string"



    SDT_Location:
      properties:
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        LocationName:
          description: "Location Name"
          type: "string"
        LocationCountry:
          description: "Location Country"
          type: "string"
        LocationCity:
          description: "Location City"
          type: "string"
        LocationZipCode:
          description: "Location Zip Code"
          type: "string"
        LocationAddressLine1:
          description: "Location Address Line1"
          type: "string"
        LocationAddressLine2:
          description: "Location Address Line2"
          type: "string"
        LocationEmail:
          description: "Location Email"
          type: "string"
        LocationPhone:
          description: "Location Phone"
          type: "string"
        LocationDescription:
          description: "Location Description"
          type: "string"



    SDT_AgendaLocation:
      properties:
        AgendaCalendarId:
          description: "Agenda Calendar Id"
          type: "string"
          format: "uuid"
        AgendaCalendarTitle:
          description: "Agenda Calendar Title"
          type: "string"
        AgendaCalendarStartDate:
          description: "Agenda Calendar Start Date"
          type: "string"
          format: "date-time"
        AgendaCalendarEndDate:
          description: "Agenda Calendar End Date"
          type: "string"
          format: "date-time"
        AgendaCalendarAllDay:
          description: "Agenda Calendar All Day"
          type: "boolean"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"



    Trn_Media:
      properties:
        MediaId:
          description: "Media Id"
          type: "string"
          format: "uuid"
        MediaName:
          description: "Media Name"
          type: "string"
        MediaImage:
          description: "Media Image"
          type: "string"
        MediaSize:
          description: "Media Size"
          type: "integer"
          format: "int64"
        MediaType:
          description: "Media Type"
          type: "string"
        MediaUrl:
          description: "Media Url"
          type: "string"



    SDT_ProductService:
      properties:
        ProductServiceId:
          description: "Product Service Id"
          type: "string"
          format: "uuid"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        ProductServiceName:
          description: "Product Service Name"
          type: "string"
        ProductServiceTileName:
          description: "Product Service Tile Name"
          type: "string"
        ProductServiceDescription:
          description: "Product Service Description"
          type: "string"
        ProductServiceClass:
          description: "Product Service Class"
          type: "string"
        ProductServiceImage:
          description: "Product Service Image"
          type: "string"
        ProductServiceGroup:
          description: "Product Service Group"
          type: "string"
        SupplierGenId:
          description: "Supplier Gen Id"
          type: "string"
          format: "uuid"
        SupplierGenCompanyName:
          description: "Company Name"
          type: "string"
        SupplierAgbId:
          description: "Supplier Agb Id"
          type: "string"
          format: "uuid"
        SupplierAgbName:
          description: "Supplier Agb Name"
          type: "string"
        CallToActions:
          description: "SDT_Call To Action"
          type: array
          items:
            $ref: "#/components/schemas/SDT_CallToAction_SDT_CallToActionItem"



    SDT_CallToAction_SDT_CallToActionItem:
      properties:
        CallToActionId:
          description: "Call To Action Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        ProductServiceId:
          description: "Product Service Id"
          type: "string"
          format: "uuid"
        CallToActionName:
          description: "Call To Action Name"
          type: "string"
        CallToActionType:
          description: "Call To Action Type"
          type: "string"
        CallToActionPhone:
          description: "Call To Action Phone"
          type: "string"
        CallToActionPhoneCode:
          description: "Call To Action Phone Code"
          type: "string"
        CallToActionPhoneNumber:
          description: "Call To Action Phone Number"
          type: "string"
        CallToActionUrl:
          description: "Call To Action Url"
          type: "string"
        CallToActionEmail:
          description: "Call To Action Email"
          type: "string"
        LocationDynamicFormId:
          description: "Location Dynamic Form Id"
          type: "string"
          format: "uuid"
        WWPFormId:
          description: "WWPForm Id"
          type: "integer"
          format: "int32"
        WWPFormVersionNumber:
          description: "WWPForm Version Number"
          type: "integer"
          format: "int32"
        WWPFormReferenceName:
          description: "WWPForm Reference Name"
          type: "string"
        WWPFormTitle:
          description: "WWPForm Title"
          type: "string"
        WWPFormDate:
          description: "WWPForm Date"
          type: "string"
          format: "date-time"
        WWPFormIsWizard:
          description: "WWPForm Is Wizard"
          type: "boolean"
        WWPFormResume:
          description: "WWPForm Resume"
          type: "integer"
          format: "int32"
        WWPFormResumeMessage:
          description: "WWPForm Resume Message"
          type: "string"
        WWPFormValidations:
          description: "WWPForm Validations"
          type: "string"
        WWPFormInstantiated:
          description: "WWPForm Instantiated"
          type: "boolean"
        WWPFormLatestVersionNumber:
          description: "WWPForm Latest Version Number"
          type: "integer"
          format: "int32"
        WWPFormType:
          description: "WWPForm Type"
          type: "integer"
          format: "int32"
        WWPFormSectionRefElements:
          description: "WWPForm Section Ref Elements"
          type: "string"
        WWPFormIsForDynamicValidations:
          description: "WWPForm Is For Dynamic Validations"
          type: "boolean"



 
