openapi: 3.0.0
info:
  title: "API_ResidentService"
  description: "API Services"
  version: "20241126121430"
servers:
  - url: https://staging.comforta.yukon.software//api
paths:
components:
  schemas:
  
 
