openapi: 3.0.0
info:
  title: "API_ToolBoxService"
  description: "API_Tool Box Service"
  version: "20241114040210"
servers:
  - url: https://staging.comforta.yukon.software/api
paths:
  /toolbox/pages/list2:
    get:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.GetPages"
      summary: "Get Pages"
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_Page"  

        404:
          description: "Not found"

  /toolbox/pages:
    get:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.PagesAPI"
      summary: "Pages API"
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_MobilePage"  

        404:
          description: "Not found"

  /media/upload:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.UploadMedia"
      summary: "UploadMedia"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadMediaInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trn_Media"  

        404:
          description: "Not found"

  /toolbox/content-pages:
    get:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.ContentPagesAPI"
      summary: "Content Pages API"
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_ContentPage"  

        404:
          description: "Not found"

  /toolbox/singlepage:
    get:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.GetSinglePage"
      summary: "Get Single Page"
      parameters:
        - name: "Pageid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Page"  

        404:
          description: "Not found"

  /toolbox/pages/list:
    get:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.ListPages"
      summary: "Get Pages"
      parameters:
        - name: "Locationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
        - name: "Organisationid"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "uuid"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SDT_PageStructure"  

        404:
          description: "Not found"

  /toolbox/create-page:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.CreatePage"
      summary: "Create Page"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/create-content-page:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.CreateContentPage"
      summary: "Create Page"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateContentPageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/save-page:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.SavePage"
      summary: "Save Page"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SavePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/update-page:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.UpdatePage"
      summary: "Update Page"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePageInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/add-page-children:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.AddPageCildren"
      summary: "Add Page CHildren"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPageCildrenInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "string"


        404:
          description: "Not found"

  /toolbox/update-location-theme:
    post:
      tags:
        - API_ToolBoxService  
      operationId: "API_ToolBoxService.UpdateLocationTheme"
      summary: "Update Location Theme"
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLocationThemeInput"
      
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SDT_Theme"  

        404:
          description: "Not found"

components:
  schemas:
    UploadMediaInput:  
      properties:
        MediaId:
          type: "string"
          format: "uuid"
        MediaName:
          type: "string"
        MediaImageData:
          type: "string"
        MediaSize:
          type: "integer"
          format: "int64"
        MediaType:
          type: "string"




    CreatePageInput:  
      properties:
        PageName:
          type: "string"

    CreateContentPageInput:  
      properties:
        PageId:
          type: "string"
          format: "uuid"

    SavePageInput:  
      properties:
        PageId:
          type: "string"
          format: "uuid"
        PageJsonContent:
          type: "string"
        PageGJSHtml:
          type: "string"
        PageGJSJson:
          type: "string"
        SDT_Page:
          description: "SDT_Page"
          $ref: "#/components/schemas/SDT_Page"

    UpdatePageInput:  
      properties:
        PageId:
          type: "string"
          format: "uuid"
        PageJsonContent:
          type: "string"
        PageGJSHtml:
          type: "string"
        PageGJSJson:
          type: "string"
        PageIsPublished:
          type: "boolean"

    AddPageCildrenInput:  
      properties:
        ParentPageId:
          type: "string"
          format: "uuid"
        ChildPageId:
          type: "string"
          format: "uuid"

    UpdateLocationThemeInput:  
      properties:
        ThemeId:
          type: "string"
          format: "uuid"
        LocationId:
          type: "string"
          format: "uuid"
        OrganisationId:
          type: "string"
          format: "uuid"
  
    SDT_Page:
      properties:
        PageId:
          description: "Page Id"
          type: "string"
          format: "uuid"
        PageName:
          description: "Page Name"
          type: "string"
        Theme:
          description: "SDT_Theme"
          $ref: "#/components/schemas/SDT_Theme"
        PageIsPublished:
          description: "Page Is Published"
          type: "boolean"
        PageGJSJson:
          description: "Page GJSJson"
          type: "string"
        PageGJSHtml:
          description: "Page GJSHtml"
          type: "string"
        PageJsonContent:
          description: "Page Json Content"
          type: "string"
        PageIsContentPage:
          description: "Page Is Content Page"
          type: "boolean"
        PageChildren:
          description: "SDT_Page Children"
          type: array
          items:
            $ref: "#/components/schemas/SDT_PageChildren"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        Row:
          description: "SDT_Row"
          type: array
          items:
            $ref: "#/components/schemas/SDT_Row"



    SDT_MobilePage:
      properties:
        PageId:
          description: "Page Id"
          type: "string"
          format: "uuid"
        PageName:
          description: "Page Name"
          type: "string"
        Theme:
          description: "SDT_Theme"
          $ref: "#/components/schemas/SDT_Theme"
        PageIsPublished:
          description: "Page Is Published"
          type: "boolean"
        PageIsContentPage:
          description: "Page Is Content Page"
          type: "boolean"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        Row:
          description: "SDT_Row"
          type: array
          items:
            $ref: "#/components/schemas/SDT_Row"



    Trn_Media:
      properties:
        MediaId:
          description: "Media Id"
          type: "string"
          format: "uuid"
        MediaName:
          description: "Media Name"
          type: "string"
        MediaImage:
          description: "Media Image"
          type: "string"
        MediaSize:
          description: "Media Size"
          type: "integer"
          format: "int64"
        MediaType:
          description: "Media Type"
          type: "string"
        MediaUrl:
          description: "Media Url"
          type: "string"



    SDT_ContentPage:
      properties:
        PageId:
          description: "Page Id"
          type: "string"
          format: "uuid"
        PageName:
          description: "Page Name"
          type: "string"
        ProductServiceImage:
          description: "Product Service Image"
          type: "string"
        ProductServiceDescription:
          description: "Product Service Description"
          type: "string"
        CallToAction:
          description: "SDT_Call To Action"
          type: array
          items:
            $ref: "#/components/schemas/SDT_CallToAction_SDT_CallToActionItem"



    SDT_PageStructure:
      properties:
        Id:
          description: "Id"
          type: "string"
          format: "uuid"
        Name:
          description: "Name"
          type: "string"
        Children:
          description: "SDT_Page Children"
          type: array
          items:
            $ref: "#/components/schemas/SDT_PageChildren"



    SDT_Theme:
      properties:
        Trn_ThemeId:
          description: "Trn_Theme Id"
          type: "string"
          format: "uuid"
        Trn_ThemeName:
          description: "Trn_Theme Name"
          type: "string"
        Trn_ThemeFontFamily:
          description: "Trn_Theme Font Family"
          type: "string"
        Trn_ThemeFontSize:
          description: "Trn_Theme Font Size"
          type: "integer"
          format: "int32"



    SDT_CallToAction_SDT_CallToActionItem:
      properties:
        CallToActionId:
          description: "Call To Action Id"
          type: "string"
          format: "uuid"
        OrganisationId:
          description: "Organisation Id"
          type: "string"
          format: "uuid"
        LocationId:
          description: "Location Id"
          type: "string"
          format: "uuid"
        ProductServiceId:
          description: "Product Service Id"
          type: "string"
          format: "uuid"
        CallToActionName:
          description: "Call To Action Name"
          type: "string"
        CallToActionType:
          description: "Call To Action Type"
          type: "string"
        CallToActionPhone:
          description: "Call To Action Phone"
          type: "string"
        CallToActionPhoneCode:
          description: "Call To Action Phone Code"
          type: "string"
        CallToActionPhoneNumber:
          description: "Call To Action Phone Number"
          type: "string"
        CallToActionUrl:
          description: "Call To Action Url"
          type: "string"
        CallToActionEmail:
          description: "Call To Action Email"
          type: "string"
        LocationDynamicFormId:
          description: "Location Dynamic Form Id"
          type: "string"
          format: "uuid"
        WWPFormId:
          description: "WWPForm Id"
          type: "integer"
          format: "int32"
        WWPFormVersionNumber:
          description: "WWPForm Version Number"
          type: "integer"
          format: "int32"
        WWPFormReferenceName:
          description: "WWPForm Reference Name"
          type: "string"
        WWPFormTitle:
          description: "WWPForm Title"
          type: "string"
        WWPFormDate:
          description: "WWPForm Date"
          type: "string"
          format: "date-time"
        WWPFormIsWizard:
          description: "WWPForm Is Wizard"
          type: "boolean"
        WWPFormResume:
          description: "WWPForm Resume"
          type: "integer"
          format: "int32"
        WWPFormResumeMessage:
          description: "WWPForm Resume Message"
          type: "string"
        WWPFormValidations:
          description: "WWPForm Validations"
          type: "string"
        WWPFormInstantiated:
          description: "WWPForm Instantiated"
          type: "boolean"
        WWPFormLatestVersionNumber:
          description: "WWPForm Latest Version Number"
          type: "integer"
          format: "int32"
        WWPFormType:
          description: "WWPForm Type"
          type: "integer"
          format: "int32"
        WWPFormSectionRefElements:
          description: "WWPForm Section Ref Elements"
          type: "string"
        WWPFormIsForDynamicValidations:
          description: "WWPForm Is For Dynamic Validations"
          type: "boolean"



    SDT_Col:
      properties:
        Tile:
          description: "SDT_Tile"
          $ref: "#/components/schemas/SDT_Tile"



    SDT_PageChildren:
      properties:
        Id:
          description: "Id"
          type: "string"
          format: "uuid"
        Name:
          description: "Name"
          type: "string"



    SDT_Row:
      properties:
        Col:
          description: "SDT_Col"
          type: array
          items:
            $ref: "#/components/schemas/SDT_Col"



    SDT_Tile:
      properties:
        TileId:
          description: "Tile Id"
          type: "string"
          format: "uuid"
        TileName:
          description: "Tile Name"
          type: "string"
        TileText:
          description: "Tile Text"
          type: "string"
        TileTextColor:
          description: "Tile Text Color"
          type: "string"
        TileTextAlignment:
          description: "Tile Text Alignment"
          type: "string"
        TileIcon:
          description: "Tile Icon"
          type: "string"
        TileIconColor:
          description: "Tile Icon Color"
          type: "string"
        TileIconAlignment:
          description: "Tile Icon Alignment"
          type: "string"
        TileBGColor:
          description: "Tile BGColor"
          type: "string"
        TileBGImageUrl:
          description: "Tile BGImage Url"
          type: "string"
        TileBGImageOpacity:
          description: "Tile BGImage Opacity"
          type: "integer"
          format: "int32"
        TileAction:
          description: "SDT_Tile Action"
          $ref: "#/components/schemas/SDT_TileAction"



    SDT_TileAction:
      properties:
        ObjectType:
          description: "Object Type"
          type: "string"
        ObjectId:
          description: "Object Id"
          type: "string"
          format: "uuid"



 
